### ISSUE TITLE
How to use custom env?

### ISSUE THREAD

**Issue by rrfaria** [schatty/d4pg-pytorch#1]
First of all I would like to say you did a pretty good job with this repo.

I would like to ask you a advice, how can I use this repo with a custom openai env?

**Comment by schatty** [comment]
Thanks, @rrfaria! Unfortunately I couldn't reproduce great results from the paper, maybe I should try it with more cores available. 

I think this wouldn't be a problem if your environment has the same interface as open ai gym's (make, reset and step methods). If I misunderstood the issue, please provide me details (:
